name: zaimu

services:
  backend:
    image: ghcr.io/hyoretsu/zaimu_backend:latest
    env_file: .env
    networks:
      - postgres
      - proxy
    restart: always
    labels:
      caddy: api.zaimu.hyoretsu.com
      caddy.reverse_proxy: "{{upstreams 3333}}"

  frontend:
    image: ghcr.io/hyoretsu/zaimu_frontend:latest
    depends_on:
      - backend
    env_file: .env
    networks:
      - postgres
      - proxy
    restart: always
    labels:
      caddy: zaimu.hyoretsu.com
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  postgres:
    external: true
  proxy:
    external: true
