/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalariesRouteImport } from './routes/salaries'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesRoute = SalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debts': typeof DebtsRoute
  '/loans': typeof LoansRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debts': typeof DebtsRoute
  '/loans': typeof LoansRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/credit-cards': typeof CreditCardsRoute
  '/debts': typeof DebtsRoute
  '/loans': typeof LoansRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/salaries': typeof SalariesRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/credit-cards'
    | '/debts'
    | '/loans'
    | '/more'
    | '/recurring'
    | '/salaries'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/credit-cards'
    | '/debts'
    | '/loans'
    | '/more'
    | '/recurring'
    | '/salaries'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/credit-cards'
    | '/debts'
    | '/loans'
    | '/more'
    | '/recurring'
    | '/salaries'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DebtsRoute: typeof DebtsRoute
  LoansRoute: typeof LoansRoute
  MoreRoute: typeof MoreRoute
  RecurringRoute: typeof RecurringRoute
  SalariesRoute: typeof SalariesRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries': {
      id: '/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof SalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  CreditCardsRoute: CreditCardsRoute,
  DebtsRoute: DebtsRoute,
  LoansRoute: LoansRoute,
  MoreRoute: MoreRoute,
  RecurringRoute: RecurringRoute,
  SalariesRoute: SalariesRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
